package:
  name: vector_normalization
  version: 1.0

source:
  path: ../../

build:
  number: 0

requirements:
  build:
    - python
    - setuptools
    - numpy

  run:
    - python
    - numpy

about:
  home: https://uibcdf.org
  license: MIT License
  summary: ""
  description: |
    This package provides a simple sample case to see how a python package with f90 fortran libraries is setup and uploaded to Anaconda.
  dev_url: https://github.com/uibcdf/TestConda_withF90Libs
  doc_url: https://uibcdf.org
