package:
  name: vector_normalization
  version: 1.0

source:
  path: ../../

build:
  number: 0

requirements:
  build:
    - python
    - setuptools
    - numpy

  run:
    - python
    - numpy

about:
  home: https://uibcdf.org
  license: MIT License
  summary: ""
  description: |
    This library provides a simple test case to see how a package is uploaded to conda.
  dev_url: https://github.com/uibcdf/TestsConda_withF90Libs
  doc_url: https://uibcdf.org
