MODULE MODULE_MATH

CONTAINS

  SUBROUTINE NORMALIZE_VECT (a)
    
    DOUBLE PRECISION,DIMENSION(3),INTENT(INOUT)::a
    DOUBLE PRECISION::norm
    
    norm=sqrt(dot_product(a,a))
    a=a/norm
    
  END SUBROUTINE NORMALIZE_VECT

END MODULE MODULE_MATH
